apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-ec2-admin-ports-ingress
  annotations:
    policies.kyverno.io/title: Check EC2 Admin Ports Ingress
    policies.kyverno.io/category: AWS EC2 Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      EC2 security groups should not allow ingress from 0.0.0.0/0 to remote server administration ports.
      This policy checks whether an Amazon EC2 security group allows ingress from 0.0.0.0/0 to remote server administration ports (ports 22 and 3389). 
      The policy fails if the security group allows ingress from 0.0.0.0/0 to port 22 or 3389. Security groups provide stateful filtering of ingress and egress 
      network traffic to AWS resources. It is recommended that no security group allow unrestricted ingress 
      access to remote server administration ports, such as SSH to port 22 and RDP to port 3389, using either the TDP (6), UDP (17), or ALL (-1) protocols. 
      Permitting public access to these ports increases resource attack surface and the risk of resource compromise.
spec:
  rules:
    - name: check-ec2-admin-ports-ingress
      match:
        all:
        - (SecurityGroups[?GroupName] || `[]` | length(@) > `0`): true
      context:
        - name: disallowedPorts
          variable:
          - 22
          - 3389
      assert:
        all:
        - message: >-
            EC2 security group should not allow ingress from 0.0.0.0/0 to remote server administration ports (ports 22 and 3389)
          check:
            ~.(SecurityGroups):
                ~.(IpPermissions[?contains($disallowedPorts, ToPort)]):
                    ~.(IpRanges):
                        (CidrIp != '0.0.0.0/0'): true

