apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-ec2-vpc-tags
  annotations:
    policies.kyverno.io/title: Check EC2 VPC Tags
    policies.kyverno.io/category: AWS EC2 Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/description: >-
      This control checks whether an Amazon Virtual Private Cloud (Amazon VPC) has tags with the specific keys
      defined in the parameter requiredTagKeys. The control fails if the Amazon VPC doesn't have any tag keys or if it doesn't 
      have all the keys specified in the parameter requiredTagKeys. If the parameter requiredTagKeys isn't provided, the control only checks 
      for the existence of a tag key and fails if the Amazon VPC isn't tagged with any key. System tags, which are automatically applied and begin with aws:, 
      are ignored. A tag is a label that you assign to an AWS resource, and it consists of a key and an optional value. 
      You can create tags to categorize resources by purpose, owner, environment, or other criteria. Tags can help you identify, organize, search for, and filter resources. 
      Tagging also helps you track accountable resource owners for actions and notifications.
spec:
  rules:
    - name: check-ec2-vpc-tags
      match:
        all:
        - (Vpcs[?VpcId] || `[]` | length(@) > `0`): true
      context:
      - name: requiredTagKeys
        variable: 
        - 'Environment' 
        - 'Owner'
      assert:
        all:
        - message: VPCs must be tagged with the required keys 
          check:
            (Vpcs[].Tags[].Key)->keys:
                ~.($requiredTagKeys):
                    (contains($keys, @)): true
                
