apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: ec2-imdsv2-check
  annotations:
    policies.kyverno.io/title: EC2 IMDSv2 Check
    policies.kyverno.io/category: AWS EC2 Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      This policy checks whether your EC2 instance metadata version is configured with 
      Instance Metadata Service Version 2 (IMDSv2). The policy passes if HttpTokens is set to required for IMDSv2. The policy fails if HttpTokens is set to optional.
      You use instance metadata to configure or manage the running instance. The IMDS provides access to temporary, frequently rotated credentials. These credentials remove the need to hard code or distribute sensitive credentials to instances manually or programmatically. The IMDS is attached locally to every EC2 instance. It runs on a special "link local" IP address of 169.254.169.254. This IP address is only accessible by software that runs on the instance.
      Version 2 of the IMDS adds new protections for the following types of vulnerabilities. 
      These vulnerabilities could be used to try to access the IMDS.
      - Open website application firewalls
      - Open reverse proxies
      - Server-side request forgery (SSRF) vulnerabilities
      - Open Layer 3 firewalls and network address translation (NAT)
spec:
  rules:
    - name: ec2-imdsv2-check
      match:
        all:
        - (Reservations[].Instances[] || `[]` | length(@) > `0`): true
      assert:
        all:
        - message: EC2 instances should use Instance Metadata Service Version 2 (IMDSv2)
          check:
            ~.(Reservations):
                ~.(Instances):
                    (MetadataOptions):
                      (HttpEndpoint == 'disabled' || HttpTokens == 'required'): true

