apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: subnet-auto-assign-public-ip-disabled
  annotations:
    policies.kyverno.io/title: Subnet Auto Assign Public IP Disabled
    policies.kyverno.io/category: AWS EC2 Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy checks whether the assignment of public IPs in Amazon Virtual Private Cloud (Amazon VPC) subnets have MapPublicIpOnLaunch set to FALSE. 
      The policy passes if the flag is set to FALSE.
      All subnets have an attribute that determines whether a network interface created in the subnet automatically receives a public IPv4 address. 
      Instances that are launched into subnets that have this attribute enabled have a public IP address assigned to their primary network interface.
      Public IP addresses can make EC2 instances directly accessible from the internet, which might not always be desirable from a security or compliance standpoint. 
      In many cases, you might not want your EC2 instances to have public IP addresses unless they need to be publicly accessible. 
      Having a public IP address can expose your EC2 instance to potential security risks, such as unauthorized access or attacks.
spec:
  rules:
    - name: subnet-auto-assign-public-ip-disabled
      match:
        all:
        - (Subnets[?SubnetArn] || `[]` | length(@) > `0`): true
      assert:
        all:
        - message: EC2 subnets should not automatically assign public IP addresses
          check:
            ~.(Subnets):
                (MapPublicIpOnLaunch): false
                    

