apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-secrets-encryption
  annotations:
    policies.kyverno.io/title: Check Cluster Secrets Encryption
    policies.kyverno.io/category: EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Cluster secrets encryption should be enabled.
spec:
  rules:
    - name: check-secrets-encryption
      match:
        all:
        - (cluster.encryptionConfig != null): true
      assert:
        all:
          - message: "Secrets encryption is enabled. The field cluster.encryptionConfig is defined for secrets."
            check:
              cluster:
                (encryptionConfig[].resources[] | contains(@, 'secrets')): true # secrets is the only supported value for resources list.
                  
