apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-ec2-iam-role
  annotations:
    policies.kyverno.io/title: check-ec2-iam-role
    policies.kyverno.io/category: AWS EC2 Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      An IAM role acts as an identity with specific permission policies that determine the allowed and disallowed actions within AWS. 
      Creating IAM roles and attaching them to manage permissions for EC2 instances ensures that access is controlled 
      and temporary credentials are used, enhancing security.
spec:
  rules:
    - name: check-ec2-iam-role
      match:
        all:
        - (Reservations[].Instances[] || `[]` | length(@) > `0`): true
      assert:
        all:
        - message: IAM Instance Profile must be attached to EC2 instances
          check:
            ~.(Reservations):
                ~.(Instances):
                    (IamInstanceProfile != null): true

