apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-supported-k8s-version
  annotations:
    policies.kyverno.io/title: Check Supported K8s Version
    policies.kyverno.io/category: EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy checks that EKS clusters are on a standard supported Kubernetes version
spec:
  rules:
    - name: check-supported-k8s-version
      match:
        all:
        - (cluster.arn != null): true
      context:
      - name: supported_k8s_versions
        variable: 
        - '1.29'
        - '1.30'
        - '1.31'
      assert:
        all:
        - message: "Version specified must be one of these suppported versions ['1.29', '1.30', '1.31']"
          check:
            cluster:
              version: 
                (contains($supported_k8s_versions, @)): true 

